var APPROVED_DRUGS_DATA = [
  {
    id: "donepezil",
    name_cn: "多奈哌齐",
    name_en: "Donepezil",
    brand_name: "安理申 / Aricept",
    company: "卫材（Eisai）/ 辉瑞（Pfizer）",
    drug_class: "胆碱酯酶抑制剂",
    mechanism: "可逆性抑制乙酰胆碱酯酶，增加大脑突触间隙乙酰胆碱水平，暂时改善认知功能。不能治愈AD，疾病本身仍在进展。",
    indication: "轻度、中度或重度阿尔茨海默病症状的治疗",
    dosage: "口服。初始5mg/天，每晚睡前服用，至少维持1个月；之后根据临床评估可增至10mg/天。推荐最大剂量10mg/天。",
    adverse_reactions: "最常见：腹泻、肌肉痉挛、乏力、恶心、呕吐、失眠。其他：心动过缓、晕厥、癫痫发作、体重下降。",
    contraindications: "对盐酸多奈哌齐或哌啶衍生物过敏者禁用",
    approval_date: "1996年（FDA）",
    approval_body: "FDA / NMPA / EMA",
    price: "医保乙类；10mg/片约162元，月费用约486元",
    insurance: "医保乙类",
    label_url: "https://www.aricept.com/docs/pdf/aricept_PI.pdf",
    label_source: "FDA官方说明书 / 卫材官网",
    references: [
      {source: "FDA说明书 (Aricept PI)", url: "https://www.aricept.com/docs/pdf/aricept_PI.pdf"},
      {source: "丁香园用药助手", url: "https://drugs.dxy.cn/business/drug/81284.htm"},
      {source: "国家医保局2026年申报材料", url: "https://www.nhsa.gov.cn/attach/Ypsn2026/YPSW202600164/YPSW202600164.pdf"}
    ],
    status: "已上市",
    sort_order: 1
  },
  {
    id: "rivastigmine",
    name_cn: "卡巴拉汀（利斯的明）",
    name_en: "Rivastigmine",
    brand_name: "艾斯能 / Exelon",
    company: "诺华（Novartis）/ 绿叶制药",
    drug_class: "胆碱酯酶抑制剂（双重抑制）",
    mechanism: "同时抑制乙酰胆碱酯酶和丁酰胆碱酯酶，增加脑内乙酰胆碱水平。透皮贴剂可减少胃肠道不良反应。",
    indication: "轻、中度阿尔茨海默病的症状治疗",
    dosage: "口服胶囊：起始1.5mg每日2次，每2周递增3mg/天，最大6mg每日2次（12mg/天）。透皮贴剂：起始4.6mg/24h，4周后增至9.5mg/24h，最大13.3mg/24h。",
    adverse_reactions: "最常见：恶心（38%）、呕吐（23%）、腹泻，特别是剂量递增期。女性更易出现胃肠道反应和体重下降。透皮贴剂：局部皮肤反应。",
    contraindications: "对卡巴拉汀或氨基甲酸衍生物过敏者禁用",
    approval_date: "2000年（FDA）",
    approval_body: "FDA / NMPA / EMA",
    price: "医保乙类",
    insurance: "医保乙类",
    label_url: "https://drugs.dxy.cn/business/drug/92293.htm",
    label_source: "丁香园用药助手 / NMPA",
    references: [
      {source: "丁香园用药助手（胶囊）", url: "https://drugs.dxy.cn/business/drug/92293.htm"},
      {source: "丁香园用药助手（透皮贴）", url: "https://drugs.dxy.cn/business/drug/208944.htm"},
      {source: "EMA产品信息", url: "https://www.medicines.org.uk/emc/product/100253/smpc"}
    ],
    status: "已上市",
    sort_order: 2
  },
  {
    id: "galantamine",
    name_cn: "加兰他敏",
    name_en: "Galantamine",
    brand_name: "Reminyl / 诺华",
    company: "诺华（Novartis）/ 多家仿制药",
    drug_class: "胆碱酯酶抑制剂 + 烟碱受体调节剂",
    mechanism: "抑制乙酰胆碱酯酶，同时作为烟碱型乙酰胆碱受体（nAChR）的变构调节剂，增强胆碱能神经传递。",
    indication: "轻度至中度阿尔茨海默病的症状治疗",
    dosage: "普通片：起始4mg每日2次（8mg/天），4周后增至8mg每日2次（16mg/天），可再增至12mg每日2次（24mg/天）。缓释胶囊：起始8mg/天，4周后16mg/天，可再增至24mg/天。建议随餐服用，保证充足饮水。",
    adverse_reactions: "最常见：恶心、呕吐、腹泻等胃肠道反应。其他：心动过缓、晕厥、体重下降、皮肤过敏。需密切监测心率变化。",
    contraindications: "对加兰他敏或本品中任何辅料过敏者禁用",
    approval_date: "2001年（FDA）",
    approval_body: "FDA / EMA",
    price: "医保乙类",
    insurance: "医保乙类",
    label_url: "https://www.accessdata.fda.gov/spl/data/18fd723e-a794-e28f-e063-6294a90a62bb/18fd723e-a794-e28f-e063-6294a90a62bb.xml",
    label_source: "FDA Access Data",
    references: [
      {source: "FDA说明书 (Galantamine Tablets)", url: "https://www.accessdata.fda.gov/spl/data/18fd723e-a794-e28f-e063-6294a90a62bb/18fd723e-a794-e28f-e063-6294a90a62bb.xml"},
      {source: "FDA说明书 (缓释胶囊)", url: "https://www.accessdata.fda.gov/spl/data/bd0edadf-df7d-48a4-9b38-377aa66720ad/bd0edadf-df7d-48a4-9b38-377aa66720ad.xml"}
    ],
    status: "已上市",
    sort_order: 3
  },
  {
    id: "memantine",
    name_cn: "美金刚",
    name_en: "Memantine",
    brand_name: "易倍申 / Ebixa / Namenda",
    company: "灵北（Lundbeck）/ 多家仿制药",
    drug_class: "NMDA受体拮抗剂",
    mechanism: "非竞争性拮抗N-甲基-D-天冬氨酸（NMDA）受体，调节谷氨酸能神经传递，减少兴奋性毒性，延缓中重度AD患者功能衰退。常与胆碱酯酶抑制剂联用。",
    indication: "治疗中度至重度阿尔茨海默型痴呆",
    dosage: "口服。起始5mg/天，第2周10mg/天，第3周15mg/天，第4周起维持20mg/天（可分2次服用，每次10mg）。可空腹或随食物服用。肾功能不全需调整剂量。",
    adverse_reactions: "最常见：头晕（7%）、头痛（5.2%）、便秘（4.6%）、嗜睡（3.4%）、高血压（4.1%）。其他：意识混乱、幻觉。",
    contraindications: "对美金刚或本品中任何辅料过敏者禁用",
    approval_date: "2003年（FDA）",
    approval_body: "FDA / NMPA / EMA",
    price: "医保乙类；20mg/片约10-20元",
    insurance: "医保乙类",
    label_url: "https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=a7b76864-6de7-45f6-be5b-5ecfca811627",
    label_source: "FDA DailyMed / EMA / 灵北官网",
    references: [
      {source: "FDA DailyMed (口服液)", url: "https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=a7b76864-6de7-45f6-be5b-5ecfca811627"},
      {source: "FDA DailyMed (缓释胶囊)", url: "https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=24290655-47f3-4042-a977-a832c5161d2c"},
      {source: "EMA产品信息", url: "https://www.ema.europa.eu/documents/product-information/memantine-lek-epar-product-information_en.pdf"}
    ],
    status: "已上市",
    sort_order: 4
  },
  {
    id: "lecanemab",
    name_cn: "仑卡奈单抗",
    name_en: "Lecanemab",
    brand_name: "乐意保 / Leqembi / IQLIK",
    company: "卫材（Eisai）/ 渤健（Biogen）",
    drug_class: "抗Aβ单克隆抗体（疾病修饰治疗）",
    mechanism: "人源化IgG1单克隆抗体，选择性结合聚集性β淀粉样蛋白（Aβ），包括可溶性寡聚体和不溶性斑块，促进小胶质细胞介导的Aβ清除，延缓疾病进展。",
    indication: "治疗早期阿尔茨海默病，包括轻度认知障碍（MCI）和轻度痴呆阶段，需确认存在Aβ病理。",
    dosage: "静脉输注：10mg/kg，每2周一次，输注时间约1小时。18个月后可继续每2周一次，或转为维持剂量每4周一次。皮下注射（IQLIK）：起始500mg/周（2次250mg注射），维持期360mg/周。治疗前需确认Aβ病理，建议检测ApoE ε4基因型。",
    adverse_reactions: "最常见（≥10%）：输注相关反应、头痛、ARIA-E（淀粉样蛋白相关成像异常-脑水肿）。其他：ARIA-H（微出血/含铁血黄素沉积）、恶心、发热。ApoE ε4纯合子患者ARIA风险更高。",
    contraindications: "对仑卡奈单抗或任何辅料严重超敏反应者禁用。脑出血风险患者慎用。",
    approval_date: "2023年1月（FDA加速批准），2023年7月（FDA完全批准），2024年1月（中国NMPA）",
    approval_body: "FDA / NMPA / EMA / PMDA",
    price: "美国$26,500/年；中国约2760元/瓶（200mg/2ml），500mg/5ml规格",
    insurance: "2024年纳入国家医保谈判目录；美国Medicare覆盖",
    label_url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761269s012s015lbl.pdf",
    label_source: "FDA官方说明书 / 卫材官网",
    references: [
      {source: "FDA说明书 (2025年8月更新)", url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761269s012s015lbl.pdf"},
      {source: "国家医保局2025年申报材料", url: "https://www.nhsa.gov.cn/attach/Ypsn2025/YPSW202500485/YPSW202500485.pdf"},
      {source: "卫材中国官网", url: "https://www.eisai.com.cn/category/news-zh/"},
      {source: "Alzheimer's Association", url: "https://www.alz.org/alzheimers-dementia/treatments/lecanemab-leqembi"},
      {source: "CLARITY-AD试验 (NEJM 2023)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2212948"}
    ],
    status: "已上市",
    sort_order: 5
  },
  {
    id: "donanemab",
    name_cn: "多奈单抗",
    name_en: "Donanemab",
    brand_name: "Kisunla",
    company: "礼来（Eli Lilly and Company）",
    drug_class: "抗Aβ单克隆抗体（疾病修饰治疗）",
    mechanism: "人源化IgG1单克隆抗体，靶向N端焦谷氨酸化β淀粉样蛋白（pGlu3-Aβ），选择性结合淀粉样斑块，促进清除。独特之处：达到斑块清除后可停药，实现有限疗程。",
    indication: "治疗成人早期症状性阿尔茨海默病，包括轻度认知障碍（MCI）和轻度痴呆阶段，需确认存在Aβ病理。",
    dosage: "静脉输注，每4周一次，输注时间约30分钟。2025年更新的逐步递增方案：第1次350mg，第2次700mg，第3次1050mg，第4次起1400mg。达到淀粉样斑块清除标准后可停止治疗。治疗前需确认Aβ病理和ApoE基因型。",
    adverse_reactions: "最常见：ARIA-E（脑水肿）、ARIA-H（微出血）、头痛、输液相关反应。ApoE ε4纯合子患者ARIA风险显著升高。其他：恶心、疲劳、超敏反应。",
    contraindications: "对多奈单抗或任何辅料严重超敏反应者禁用。脑出血/微出血风险患者慎用。",
    approval_date: "2024年7月2日（FDA）",
    approval_body: "FDA / EMA（申请中）",
    price: "美国约$32,000/年（按18个月疗程计）",
    insurance: "美国Medicare覆盖；中国尚未上市",
    label_url: "https://www.accessdata.fda.gov/drugsatfda_docs/nda/2024/761248Orig1s000Lbl.pdf",
    label_source: "FDA官方说明书 / 礼来官网",
    references: [
      {source: "FDA说明书 (2024年)", url: "https://www.accessdata.fda.gov/drugsatfda_docs/nda/2024/761248Orig1s000Lbl.pdf"},
      {source: "礼来官网Kisunla页面", url: "https://www.lilly.com/news/media/kisunla"},
      {source: "礼来HCP给药指南", url: "https://www.lilly.com/hcp/product/kisunla/dosing-use"},
      {source: "TRAILBLAZER-ALZ 2试验 (JAMA 2023)", url: "https://jamanetwork.com/journals/jama/fullarticle/2807229"},
      {source: "FDA批准新闻稿 (2024.7.2)", url: "https://investor.lilly.com/news-releases/news-release-details/lillys-kisunlatm-donanemab-azbt-approved-fda-treatment-early"}
    ],
    status: "已上市（美国）",
    sort_order: 6
  },
  {
    id: "oligomannate",
    name_cn: "甘露特钠",
    name_en: "Sodium Oligomannate (GV-971)",
    brand_name: "九期一",
    company: "上海绿谷制药有限公司",
    drug_class: "海洋来源寡糖类药物",
    mechanism: "以海洋褐藻提取物为原料制备的寡糖。官方称通过调节肠道菌群失衡、减少外周炎症细胞浸润、抑制神经炎症，从而改善认知功能。该机制仍存在学术争议，国际认可度有限。",
    indication: "用于轻度至中度阿尔茨海默病，改善患者认知功能。",
    dosage: "口服。一次3粒（450mg），一日2次。可空腹服用或与食物同服。规格：150mg/粒，42粒/盒。",
    adverse_reactions: "详见说明书。临床试验中观察到的不良反应包括：胃肠道不适、肝功能异常、皮疹等。",
    contraindications: "对本品主要成份（甘露特钠）或任何辅料过敏者禁用",
    approval_date: "2019年11月2日（NMPA有条件批准）",
    approval_body: "NMPA（中国）",
    price: "原价895元/盒，2021年医保谈判后降至296元/盒；零售价约360-365元/盒。月费用约600元（自付）。",
    insurance: "医保乙类（2021年纳入国家医保目录，国谈药，双通道管理）",
    approval_number: "国药准字H20190031",
    label_url: "https://drugs.dxy.cn/business/drug/187840/detail.htm",
    label_source: "NMPA / 丁香园用药助手",
    references: [
      {source: "NMPA批准公告 (2019.11.2)", url: "https://www.nmpa.gov.cn/zhuanti/cxylqx/cxypxx/20191102204301440.html"},
      {source: "丁香园用药助手说明书", url: "https://drugs.dxy.cn/business/drug/187840/detail.htm"},
      {source: "国家医保局2026年申报材料", url: "https://www.nhsa.gov.cn/attach/Ypsn2026/YPSW202600426/YPSW202600426.pdf"},
      {source: "腾讯新闻-甘露特钠医保报道", url: "http://news.qq.com/rain/a/20231011A03E8Y00"},
      {source: "Cell Research 2019 (GV-971机制论文)", url: "https://www.nature.com/articles/s41422-019-0216-x"}
    ],
    status: "已上市（中国）",
    sort_order: 7
  },
  {
    id: "namzaric",
    name_cn: "美金刚/多奈哌齐复方",
    name_en: "Memantine/Donepezil (Namzaric)",
    brand_name: "Namzaric",
    company: "Adamas Pharmaceuticals / 灵北（Lundbeck）",
    drug_class: "NMDA受体拮抗剂 + 胆碱酯酶抑制剂复方",
    mechanism: "美金刚（NMDA受体拮抗）与多奈哌齐（胆碱酯酶抑制）的固定剂量复方制剂，每日一次服用，提高用药依从性。",
    indication: "中度至重度阿尔茨海默病，适用于正在接受稳定剂量多奈哌齐治疗的患者",
    dosage: "口服，每日一次，睡前服用。包含美金刚缓释（7mg/14mg/21mg/28mg）+ 多奈哌齐（10mg）。根据患者当前美金刚剂量选择对应规格。",
    adverse_reactions: "与单药治疗相似：头痛、头晕、恶心、腹泻、便秘、厌食、瘀伤。",
    contraindications: "对美金刚、多奈哌齐或哌啶衍生物过敏者禁用",
    approval_date: "2014年（FDA）",
    approval_body: "FDA",
    price: "美国市场，中国未上市",
    insurance: "美国Medicare D部分",
    label_url: "",
    label_source: "FDA",
    references: [
      {source: "Alzheimer's Association治疗指南", url: "https://www.alz.org/alzheimers-dementia/treatments/medications-for-memory"}
    ],
    status: "已上市（美国）",
    sort_order: 8
  },
  {
    id: "aducanumab",
    name_cn: "阿杜卡奴单抗",
    name_en: "Aducanumab",
    brand_name: "Aduhelm",
    company: "渤健（Biogen）/ 卫材（Eisai）",
    drug_class: "抗Aβ单克隆抗体",
    mechanism: "靶向聚集性Aβ的单克隆抗体。2021年通过FDA加速批准途径上市（基于替代终点Aβ清除），但因临床获益不明确、安全性争议（ARIA）及市场反应冷淡，于2024年退市。",
    indication: "曾获批用于阿尔茨海默病治疗（加速批准）",
    dosage: "曾为静脉输注，每月一次，剂量递增",
    adverse_reactions: "ARIA-E、ARIA-H、头痛、输液反应",
    approval_date: "2021年6月（FDA加速批准）",
    approval_body: "FDA（已撤回/退市）",
    price: "曾定价$56,000/年",
    insurance: "已退市",
    label_url: "",
    label_source: "FDA（历史）",
    references: [
      {source: "Alzheimer's Association治疗指南", url: "https://www.alz.org/alzheimers-dementia/treatments/medications-for-memory"}
    ],
    status: "已退市（2024年）",
    sort_order: 9
  },
  {
    id: "tacrine",
    name_cn: "他克林",
    name_en: "Tacrine",
    brand_name: "Cognex",
    company: "Parke-Davis（辉瑞子公司）",
    drug_class: "胆碱酯酶抑制剂",
    mechanism: "全球首个获批的阿尔茨海默病治疗药物，可逆性抑制乙酰胆碱酯酶。因严重肝毒性（转氨酶升高）和需每日4次服用的不便，已退出市场。",
    indication: "曾用于轻中度阿尔茨海默病",
    dosage: "曾为口服，每日4次，剂量递增",
    adverse_reactions: "肝毒性（转氨酶升高）、恶心、呕吐、腹泻",
    approval_date: "1993年（FDA，全球首个AD药物）",
    approval_body: "FDA（已退市）",
    price: "已退市",
    insurance: "已退市",
    label_url: "",
    label_source: "FDA（历史）",
    references: [
      {source: "Alzheimer's Association治疗指南", url: "https://www.alz.org/alzheimers-dementia/treatments/medications-for-memory"}
    ],
    status: "已退市",
    sort_order: 10
  },
  {
    id: "octohydroaminoacridine",
    name_cn: "琥珀酸安维吖啶（耄安通）",
    name_en: "Octohydroaminoacridine Succinate",
    brand_name: "耄安通®",
    company: "通化金马药业集团（000766.SZ）",
    drug_class: "胆碱酯酶抑制剂（双靶点）",
    mechanism: "中国自主研发的化学1类创新药（全新化学实体，曾用名琥珀八氢氨吖啶）。双靶点抑制乙酰胆碱酯酶（AChE）和丁酰胆碱酯酶（BuChE），提高脑内乙酰胆碱水平，改善轻中度AD患者认知功能。历时20余年研发，2015年8月获NMPA III期临床批件，2021年8月完成全部入组。",
    indication: "用于轻、中度阿尔茨海默病症状的治疗",
    dosage: "口服，餐后服用。初始剂量一次2mg，一日3次，该剂量应至少维持1~2周；第三周开始增加至一次4mg，一日3次（12mg/日维持剂量）。",
    adverse_reactions: "III期临床试验显示，试验组不良反应、不良事件、重要不良事件及严重不良事件发生率与安慰剂组均无统计学差异，耐受性和安全性良好。常见不良反应以胆碱能相关胃肠道反应为主（恶心、呕吐、腹泻等），具体以说明书为准。",
    contraindications: "对本品活性成分或任何辅料过敏者禁用；严重肝功能不全患者慎用（详见说明书）",
    approval_date: "2026年6月25日（NMPA）",
    approval_body: "NMPA（国家药品监督管理局）",
    price: "挂网价：4mg 616元/盒（21片）、2mg 369元/盒（21片）；月费用约880元（4mg规格，自费）。已启动2026年国家医保目录申报",
    insurance: "未纳入医保（2026年申报中）",
    label_url: "https://www.nhsa.gov.cn/attach/Ypsn2026/YPSW202600164/YPSW202600164.pdf",
    label_source: "NMPA批准公告 / 国家医保局申报材料",
    references: [
      {source: "NMPA批准琥珀酸安维吖啶片上市公告", url: "https://www.nmpa.gov.cn/directory/web/nmpa/zhuanti/zt2023/ypgzhlfzh/shypqxgg/ggjzcx/20260714102827193.html"},
      {source: "通化金马《药品注册证书》公告（巨潮资讯）", url: "http://static.cninfo.com.cn/finalpage/2026-06-26/1225386817.PDF"},
      {source: "国家医保局2026年目录调整申报材料（含说明书用法用量）", url: "https://www.nhsa.gov.cn/attach/Ypsn2026/YPSW202600164/YPSW202600164.pdf"},
      {source: "界面新闻：耄安通正式获批报道", url: "https://m.jiemian.com/article/14658253.html"},
      {source: "上海证券报：获批公告原文", url: "http://paper.cnstock.com/html/2026-06/26/content_2235379.htm"}
    ],
    status: "已上市（中国，2026年）",
    sort_order: 11
  }
];
